### ISSUE TITLE
👋 Which license does this project have

### ISSUE THREAD

**Issue by leipert** [legrego/docker-node-fips#1]
Sorry to resurrect this old one, @legrego. But could you be so kind and add a license to this project (e.g. MIT?) so that I could use a fork of this project for some work related things.

**Comment by leipert** [comment]
cc/ @giancarlocosta

**Comment by legrego** [comment]
@giancarlocosta do you have a license preference? This originated from your work in https://github.com/giancarlocosta/node-fips, and I don't want to preempt your wishes.

**Comment by giancarlocosta** [comment]
@legrego Sorry for delay. I don't maintain this at all anymore so feel free to do anything you want!

**Comment by legrego** [comment]
Opened #2 to license this under MIT. Thanks!
